version: "3.8"
services:
  app:
    container_name: spring
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres_db:5432/blogBD
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=12345
    depends_on:
      - postgres_db
    networks:
      - spring-network

  postgres_db:
    container_name: postgres_db
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: blogBD
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge

volumes:
  postgres-data:



